project_id = "vxvzqqgnytanmsxnemft"

[functions.text-to-speech]
verify_jwt = false

[functions.fetch-voices]
verify_jwt = false

[functions.fetch-models]
verify_jwt = false

[functions.generate-speech]
verify_jwt = false

[functions.get-task]
verify_jwt = false

[functions.check-api-balance]
verify_jwt = false

[functions.list-tasks]
verify_jwt = false

[functions.delete-task]
verify_jwt = false

[functions.get-credits]
verify_jwt = false

[functions.health-check]
verify_jwt = false
